Compiling code

1.   Object detection in Video
2.   Eye blink detection
3.   Face recognition



Mounting google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
path = '/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compiled'
os.chdir(path)

Mounted at /content/drive


Importing the required libraries

In [ ]:
!pip install ultralytics
!pip install deepface
# !pip install "/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compiled/Dependencies/dlib-19.24.1-cp311-cp311-win_amd64.whl"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.6/779.6 kB 9.1 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [ ]:
import numpy as np
import pandas as pd

import cv2
from google.colab.patches import cv2_imshow
from ultralytics import YOLO

import dlib
from imutils import face_utils
from scipy.spatial import distance as dist

from deepface import DeepFace

import time

# Start timer
tic = time.time()

# Load the pre-trained model for YOLOv8
model = YOLO('yolov8m.pt')

# Path to the video
video_path = '/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compiled/inputs/Ashish.mp4'

# Run the video through the model
results = model(source=video_path, show=True, conf=0.4, save=True)

# Storing the required information in the dataframe

import pandas as pd
frames_info = pd.DataFrame(columns = ['frame_id', 'conf_score', 'object_id', 'object_name', 'x1', 'x2', 'y1', 'y2'])

count = 1

for result in results:
  for detect in result.boxes.data:
    detect = detect.cpu().numpy()
    t = pd.DataFrame({
        'frame_id':[count],
        'conf_score':[detect[4]],
        'object_id':[int(detect[5])],
        'object_name':[model.names[int(detect[5])]],
        'x1':[detect[0]],
        'x2':[detect[2]],
        'y1':[detect[1]],
        'y2':[detect[3]]
    })

    frames_info = pd.concat([frames_info, t], ignore_index = True)
  count +=1

tc = time.time()
print(tc-tic)

# Initialize an empty set to store unique object names
detected_objects = set()

# Process the results
for result in results:
    for detection in result.boxes.data:
        class_id = int(detection[5])
        class_name = model.names[class_id]
        detected_objects.add(class_name)

# Convert the set to a list to get the final list of detected objects
objects_list = list(detected_objects)
print(objects_list)
print('\n')

# Check for unauthorized objects
objects_of_interest = ["cell phone"]  # "laptop"
if any(obj in objects_list for obj in objects_of_interest):
    print("UNAUTHORISED ACCESS: Phone/Laptop is detected.")
else:
    print('Moving to eye-blink detection.\n')

    def eye_aspect_ratio(eye):
        A = dist.euclidean(eye[1], eye[5])
        B = dist.euclidean(eye[2], eye[4])
        C = dist.euclidean(eye[0], eye[3])
        ear = (A + B) / (2.0 * C)
        return ear

    EYE_AR_THRESH = 0.21
    EYE_AR_CONSEC_FRAMES = 5

    # Initialize counters
    COUNTER = 0
    TOTAL = 0

    # Initialize dlib's face detector and create the facial landmark predictor
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor('/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compiled/Dependencies/shape_predictor_68_face_landmarks.dat')

    (lStart, lEnd) = face_utils.FACIAL_LANDMARKS_IDXS["left_eye"]
    (rStart, rEnd) = face_utils.FACIAL_LANDMARKS_IDXS["right_eye"]

    # Open the video file again for eye blink detection
    cap = cv2.VideoCapture(video_path)

    # Get the width and height of the frames in the video
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # Define the codec and create VideoWriter object
    output_path = '/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compiled/outputs/output - Ashish.avi'
    out = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*'XVID'), 10, (frame_width, frame_height))

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        rects = detector(gray, 0)

        for rect in rects:
            shape = predictor(gray, rect)
            shape = face_utils.shape_to_np(shape)

            leftEye = shape[lStart:lEnd]
            rightEye = shape[rStart:rEnd]
            leftEAR = eye_aspect_ratio(leftEye)
            rightEAR = eye_aspect_ratio(rightEye)

            ear = (leftEAR + rightEAR) / 2.0

            leftEyeHull = cv2.convexHull(leftEye)
            rightEyeHull = cv2.convexHull(rightEye)
            cv2.drawContours(frame, [leftEyeHull], -1, (0, 255, 0), 1)
            cv2.drawContours(frame, [rightEyeHull], -1, (0, 255, 0), 1)

            if ear < EYE_AR_THRESH:
                COUNTER += 1
            else:
                if COUNTER >= EYE_AR_CONSEC_FRAMES:
                    TOTAL += 1
                COUNTER = 0

            cv2.putText(frame, "Blinks: {}".format(TOTAL), (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 3, (0, 0, 255), 2)

        # Write the frame to the output video file
        out.write(frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    out.release()
    cv2.destroyAllWindows()

    # Print the final number of blinks
    print(f"Total number of blinks detected: {TOTAL}")

    if not TOTAL:
        print('UNAUTHORISED ACCESS: Spoofing detected')
    else:
        print('Moving to face detection.')

        # Initialize variables to store the highest scoring person object and its corresponding frame
        highest_score = 0
        person_bbox_with_highest_score = None
        frame_with_highest_score = None

        # Open the video file again for face detection
        cap = cv2.VideoCapture(video_path)

        # Iterate over the detected frames
        for frame_idx, frame_results in enumerate(results):
            for detection in frame_results.boxes.data:
                x1, y1, x2, y2, conf, cls = detection

                # Check if the detected object is a person (assuming class '0' corresponds to 'person')
                if int(cls) == 0 and conf > highest_score:
                    highest_score = conf
                    person_bbox_with_highest_score = (int(x1), int(y1), int(x2), int(y2))

                    # Set the video frame to the current frame index
                    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
                    ret, frame_with_highest_score = cap.read()

        cap.release()

        # If a person object with the highest score is found, crop the corresponding region from the frame
        if person_bbox_with_highest_score is not None and frame_with_highest_score is not None:
            x1, y1, x2, y2 = person_bbox_with_highest_score
            cropped_person = frame_with_highest_score[y1:y2, x1:x2]
            # Display or save the cropped person image
            print(f'Frame no. {frame_idx}: {highest_score}')
            # cv2_imshow(cropped_person)
            cv2.waitKey(0)
            cv2.destroyAllWindows()


            # --------- FACE RECOGNITION ---------

            # Path to the database directory
            # db_path = "/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/Faces/train/AshishGhule"
            db_path = "/content/drive/MyDrive/Colab Notebooks/ND Face Recognition/Faces/train/AkshayFadnavis"
            suffixes = ("png", "jpg", "jpeg")

            # Initialize variables
            is_verified = False
            threshold_value = None
            matched_image_path = None
            my_img_dist = None

            for i in os.listdir(db_path):
              if i.lower().endswith(suffixes):
                my_img_path = os.path.join(db_path, i)
                try:
                  vf = DeepFace.verify(cropped_person, my_img_path, model_name = "Facenet512", enforce_detection = False)
                  if vf['distance'] < vf['threshold']:
                    is_verified = True
                    thres = vf['threshold']
                    matched_image_path = my_img_path
                    my_img_dist = vf['distance']
                    break
                except Exception as e:
                  print(f"Error processing {my_img_path}: {e}")
                  continue

            if is_verified:
              print("ACCESS GRANTED: Face verified!")
            else:
              print("ACCESS DENIED: Face not verified!")

toc = time.time()
print(f'Total time required for code running: {round((toc-tic)/60, 2)} Minutes.')


24-06-07 07:12:09 - Directory /root/.deepface created
24-06-07 07:12:09 - Directory /root/.deepface/weights created
WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()



WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/91) /content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compiled/inputs/Ashish.mp4: 640x480 1 person, 1 bottle, 1 chair, 1 laptop, 2 keyboards, 1246.3ms
video 1/1 (frame 2/91) /content/drive/MyDrive/Colab Notebooks/ND Face Recognition/compi

Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/facenet512_weights.h5
To: /root/.deepface/weights/facenet512_weights.h5
100%|██████████| 95.0M/95.0M [00:00<00:00, 197MB/s]


ACCESS DENIED: Face not verified!
Total time required for code running: 3.26 Minutes.


In [ ]:
for result in results[0]:
  for detect in result.boxes.data:
    print(detect)
    print(int(detect[5]))
    print(model.names[int(detect[5])])

tensor([1.6398e+00, 2.4897e+02, 1.0309e+03, 1.4383e+03, 9.6951e-01, 0.0000e+00], device='cuda:0')
0
person
tensor([8.9759e+02, 4.5256e+02, 1.0782e+03, 5.2730e+02, 8.8010e-01, 6.6000e+01], device='cuda:0')
66
keyboard
tensor([8.6826e+02, 2.5815e+02, 9.3462e+02, 4.1725e+02, 6.2714e-01, 3.9000e+01], device='cuda:0')
39
bottle
tensor([9.6917e+02, 2.6726e+02, 1.0794e+03, 5.0020e+02, 4.8776e-01, 6.3000e+01], device='cuda:0')
63
laptop
tensor([1.0120e+03, 3.6193e+02, 1.0795e+03, 4.3415e+02, 4.4585e-01, 6.6000e+01], device='cuda:0')
66
keyboard
tensor([4.4814e-01, 3.4749e+02, 3.4461e+02, 7.0439e+02, 4.1312e-01, 5.6000e+01], device='cuda:0')
56
chair


In [ ]:
for result in results[0]:
  for detect in result.boxes.data:
    print(detect)
    print(f'class id of objects: {int(detect[5])}')
    print(f'class id of objects: {model.names[int(detect[5])]}')
    print(f'probability of objects: {detect[4]}')

tensor([1.6398e+00, 2.4897e+02, 1.0309e+03, 1.4383e+03, 9.6951e-01, 0.0000e+00], device='cuda:0')
class id of objects: 0
class id of objects: person
probability of objects: 0.9695107340812683
tensor([8.9759e+02, 4.5256e+02, 1.0782e+03, 5.2730e+02, 8.8010e-01, 6.6000e+01], device='cuda:0')
class id of objects: 66
class id of objects: keyboard
probability of objects: 0.8800976872444153
tensor([8.6826e+02, 2.5815e+02, 9.3462e+02, 4.1725e+02, 6.2714e-01, 3.9000e+01], device='cuda:0')
class id of objects: 39
class id of objects: bottle
probability of objects: 0.627143144607544
tensor([9.6917e+02, 2.6726e+02, 1.0794e+03, 5.0020e+02, 4.8776e-01, 6.3000e+01], device='cuda:0')
class id of objects: 63
class id of objects: laptop
probability of objects: 0.4877634644508362
tensor([1.0120e+03, 3.6193e+02, 1.0795e+03, 4.3415e+02, 4.4585e-01, 6.6000e+01], device='cuda:0')
class id of objects: 66
class id of objects: keyboard
probability of objects: 0.4458509087562561
tensor([4.4814e-01, 3.4749e+02, 3

In [ ]:
import pandas as pd
frames_info = pd.DataFrame(columns = ['frame_id', 'conf_score', 'object_id', 'object_name', 'x1', 'x2', 'y1', 'y2'])

In [ ]:
frames_info

Empty DataFrame
Columns: [frame_id, conf_score, object_id, object_name, x1, x2, y1, y2]
Index: []

In [ ]:
count = 0
for result in results:
  count+=1

print(count)

91


In [ ]:
import pandas as pd
frames_info = pd.DataFrame(columns = ['frame_id', 'conf_score', 'object_id', 'object_name', 'x1', 'x2', 'y1', 'y2'])

count = 1

for result in results:
  for detect in result.boxes.data:
    detect = detect.cpu().numpy()
    t = pd.DataFrame({
        'frame_id':[count],
        'conf_score':[detect[4]],
        'object_id':[int(detect[5])],
        'object_name':[model.names[int(detect[5])]],
        'x1':[detect[0]],
        'x2':[detect[2]],
        'y1':[detect[1]],
        'y2':[detect[3]]
    })

    frames_info = pd.concat([frames_info, t], ignore_index = True)
  count +=1

In [ ]:
frames_info.shape

(534, 8)

In [ ]:
frames_info.head(10)

frame_id  conf_score object_id object_name           x1           x2  \
0        1    0.969511         0      person     1.639778  1030.891602   
1        1    0.880097        66    keyboard   897.585754  1078.195801   
2        1    0.627143        39      bottle   868.264587   934.624756   
3        1    0.487764        63      laptop   969.167053  1079.366577   
4        1    0.445852        66    keyboard  1012.021057  1079.533447   
5        1    0.413124        56       chair     0.448139   344.610809   
6        2    0.968654         0      person     1.491943  1032.163574   
7        2    0.880772        66    keyboard   897.758484  1079.046631   
8        2    0.702380        39      bottle   868.429565   934.768005   
9        2    0.443866        66    keyboard  1011.044861  1079.519043   

           y1           y2  
0  248.968597  1438.251465  
1  452.564545   527.296509  
2  258.145203   417.247345  
3  267.257629   500.196625  
4  361.933807   434.150513  
5  347.493286   704.386658  
6  248.618408  1438.023315  
7  452.493134   527.823425  
8  258.645966   417.718933  
9  360.867157   435.314148

In [ ]:
i = 0

for result in results:
  i+=1

print(i)

91


In [ ]:
i = 0

for result in results[0]:
  for detect in result.boxes.data:
    print(detect)
    i+=1

tensor([1.6398e+00, 2.4897e+02, 1.0309e+03, 1.4383e+03, 9.6951e-01, 0.0000e+00], device='cuda:0')
tensor([8.9759e+02, 4.5256e+02, 1.0782e+03, 5.2730e+02, 8.8010e-01, 6.6000e+01], device='cuda:0')
tensor([8.6826e+02, 2.5815e+02, 9.3462e+02, 4.1725e+02, 6.2714e-01, 3.9000e+01], device='cuda:0')
tensor([9.6917e+02, 2.6726e+02, 1.0794e+03, 5.0020e+02, 4.8776e-01, 6.3000e+01], device='cuda:0')
tensor([1.0120e+03, 3.6193e+02, 1.0795e+03, 4.3415e+02, 4.4585e-01, 6.6000e+01], device='cuda:0')
tensor([4.4814e-01, 3.4749e+02, 3.4461e+02, 7.0439e+02, 4.1312e-01, 5.6000e+01], device='cuda:0')
